### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by josefnpat** [iheanyi/bandcamp-dl#15]
I was able to install all the listed dependencies on Ubuntu 14.04 with something along the lines of;

```
sudo apt-get install python-mutagen python-bs4 python-requests slimit pip
sudo pip install docopt wgetter
```

When I run this I get the following error:

```
~/repos/bandcamp-dl/bandcamp-dl♠ python2 bandcamp-dl.py 
Traceback (most recent call last):
  File "bandcamp-dl.py", line 43, in <module>
    from BandcampDownloader import BandcampDownloader
  File "/home/seppi/repos/bandcamp-dl/bandcamp-dl/BandcampDownloader.py", line 7, in <module>
    from slugify import slugify
ImportError: No module named slugify
```

**Comment by mtchllbrrn** [comment]
sudo pip install slugify

**Comment by josefnpat** [comment]
nevermind; missed this.

```
pip install slugify
```

I highly suggest adding this into the docs.

**Comment by josefnpat** [comment]
I will mention something that threw me off as a non-native python2 user;

```
    ~/repos/bandcamp-dl/bandcamp-dl♠ ls -lah
    total 104K
    drwxr-xr-x 3 seppi seppi 4.0K Aug  7 18:59 .
    drwxr-xr-x 4 seppi seppi 4.0K Aug  7 18:51 ..
    -rw-r--r-- 1 seppi seppi 2.2K Aug  7 18:44 bandcamp-dl.py
    -rw-r--r-- 1 seppi seppi 3.2K Aug  7 18:44 BandcampDownloader.py
    -rw-r--r-- 1 seppi seppi 3.6K Aug  7 18:55 BandcampDownloader.pyc
    -rw-r--r-- 1 seppi seppi 2.9K Aug  7 18:44 Bandcamp.py
    -rw-r--r-- 1 seppi seppi 3.4K Aug  7 18:55 Bandcamp.pyc
    -rw-r--r-- 1 seppi seppi    0 Aug  7 18:44 __init__.py
    -rwxr-xr-x 1 seppi seppi 3.1K Aug  7 18:44 jsobj.py
    -rw-r--r-- 1 seppi seppi 3.0K Aug  7 18:55 jsobj.pyc
```

Why is `jsobj.pyc` marked as the executable and `bandcamp-dl.py` not? Shouldn't it be the other way around? This was confusing for me on the first encounter.

**Comment by josefnpat** [comment]
See Pull Request #16
